### ISSUE TITLE
Suggestion : Improvement of instructions to find the "config directory"

### ISSUE THREAD

**Issue by alexisgourdol** [lewagon/data-setup#105]
https://github.com/lewagon/data-setup/blob/master/macOS.md#custom-css

_Context : the set up was done in July 2020 on my machine. I wanted to upgrade to Python 3.8.6 and followed the steps again in June 2021_

For the custom CSS, I did not have a variable `JUPYTER_CONFIG_DIR` defined.
On Slack @gmanchon mentioned that we could find the config file with this command:
`jupyter --config-dir`
>  => it could make sense to add this on the set up page

![image](https://user-images.githubusercontent.com/7635901/123442421-c62fd400-d5cc-11eb-8785-2667d616b74f.png)

**Comment by gmanchon** [comment]
@alexisgourdol this has been fixed by the PR, thanks for reporting 🙏
