### ISSUE TITLE
Windos: Add pyenv to zsh plugin list

### ISSUE THREAD

**Issue by lislis** [lewagon/data-setup#107]
It seems like students copy the entire line of plugins in the "Disable ssh passphrase prompt" instead of just adding `ssh-agent` at the end. 
The line is missing the `pyenv` plugin though, causing errors afterwards!
https://github.com/lewagon/data-setup/blob/master/WINDOWS.md#disable-ssh-passphrase-prompt

So ideally this would be the line for the students' copy/paste convenience

```plugins=(git gitfast last-working-dir common-aliases sublime zsh-syntax-highlighting history-substring-search pyenv ssh-agent)```

**Comment by krokrob** [comment]
Solved https://github.com/lewagon/data-setup/blob/be2b564d414c7ab0018b03e6d5c956ab130bf51d/WINDOWS.md#L915
