### ISSUE TITLE
$(pyenv init --path) instead of $(pyenv init -)

### ISSUE THREAD

**Issue by RafaelAlonso** [lewagon/data-setup#111]
I've been running into this issue for quite some time now and I actually found it weird that no one pointed that out yet hahaha

Thing is, inside `~/.zshrc` we have the following line:
`type -a pyenv > /dev/null && eval "$(pyenv init -)" && eval "$(pyenv virtualenv-init -)"`

However, this returns an error in the students' terminals (`"pyenv init -" no longer sets PATH`), making `python` and `pip` unknown commands. What I found around this was to change this line to this one:
`type -a pyenv > /dev/null && eval "$(pyenv init --path)" && eval "$(pyenv virtualenv-init -)"`

If correct, I think we should change the dotfiles to make that change. Otherwise, I'd like to know what I'm missing :)

**Comment by krokrob** [comment]
Never had that problem with our students.
