### ISSUE TITLE
Windows Ubuntu - tensorflow > 1.6 not working for computers with old CPU

### ISSUE THREAD

**Issue by Yanka13** [lewagon/data-setup#147]
:warning: A student here in Paris was not able to make tensorflow 2.5.1 works, he got the following error after importing tensorflow :` illegal hardware instruction  `
it seems that he has an old CPU, according to the [doc](https://www.tensorflow.org/install/pip), starting with `TensorFlow 1.6`, binaries use [AVX instructions](https://en.wikipedia.org/wiki/Advanced_Vector_Extensions#CPUs_with_AVX) which may not run on older CPUs.
student config : INTEL(R) Celeron(R) N4030 CPU @1.10GHz 1.10 GHz
:white_check_mark:it looks like the only turnaround is to use an older version of` tensorflow (<1.6) ` or to build from source
:github: official issue : https://github.com/tensorflow/tensorflow/issues/17411
Proposition to fix this issue : check beforehand the configuration of student' computers with` $ grep flags -m1 /proc/cpuinfo | cut -d ":" -f 2 | tr '[:upper:]' '[:lower:]' | { read FLAGS; OPT="-march=native"; for flag in $FLAGS; do case "$flag" in "sse4_1" | "sse4_2" | "ssse3" | "fma" | "cx16" | "popcnt" | "avx" | "avx2") OPT+=" -m$flag";; esac; done; MODOPT=${OPT//_/\.}; echo "$MODOPT"; }`

If by executing the command, `-mavx `and/or `-mavx2 `is not shown, it can be confirmed that AVX support is missing and the source build should be done with other optimization flags displayed in the output.
[This article ](https://tech.amikelive.com/node-882/how-to-build-and-install-the-latest-tensorflow-without-cuda-gpu-and-with-optimized-cpu-performance-on-ubuntu/) explains how to build TensorFlow from sources and optimizes for the older CPU. The key is in detecting the CPU flags and enable all the CPU flags for optimization when configuring the build.
Thanks to : 
https://stackoverflow.com/questions/49094597/illegal-instruction-core-dumped-after-running-import-tensorflow

**Comment by krokrob** [comment]
I had the support for avx and avx2 as a prerequisite for the bootcamp

**Comment by brunolajoie** [comment]
We can close this one then!
