### ISSUE TITLE
Windows set up - typo in Google Cloud Platform tutorial

### ISSUE THREAD

**Issue by Yanka13** [lewagon/data-setup#148]
👉 Open an Ubuntu terminal and run the following commands

🚨 replace GITHUB_NICKNAME by your GitHub nickname

```
cd ~/code/GITHUB_NICKNAME
ls -la
```
If the command does not show the **data-challenges** and dotfiles directories, ask for a TA 🙏

Otherwise, you can proceed with the setup:

Issue => At this point of the set-up, students don't have forked/clone the **data-challenges** repository yet, it is done afterward in the Kitt instruction.

**Comment by gmanchon** [comment]
Thanks for reporting @Yanka13, I am closing the issue which it is addressed by https://github.com/lewagon/data-setup/pull/160.
