### ISSUE TITLE
reintegrate pyenv init from .zprofile to .zshrc

### ISSUE THREAD

**Issue by gmanchon** [lewagon/data-setup#150]
having the initialisation of pyenv in both `.zprofile` and `.zshrc` seems to generate some confusion

https://lewagon-alumni.slack.com/archives/G02NFDT0J/p1632938371252800?thread_ts=1632502334.175100&cid=G02NFDT0J
https://lewagon-alumni.slack.com/archives/C02EDQ2SNBE/p1633184235135600

**Comment by brunolajoie** [comment]
closed by the new VScode settings.json https://github.com/lewagon/dotfiles/pull/100
