### ISSUE TITLE
Discrepancies between packages installed and packages checked (Apple Silicon)

### ISSUE THREAD

**Issue by trouni** [lewagon/data-setup#173]
I don't have the exact list in mind again, but one of the student had a "missing package" issue when running the check, and was asked to pip install `bs4`, `tensorflow-metal` and `dtale` manually.

I think `tensorflow-metal` should not be in that check as well...

**Comment by brunolajoie** [comment]
closed by https://github.com/lewagon/data-setup/pull/170
