### ISSUE TITLE
Remove Anaconda before installing pyenv

### ISSUE THREAD

**Issue by krokrob** [lewagon/data-setup#177]
As the Udemy courses suggest our applicants to install Anaconda, the config could interfere with the `pyenv` environment.
We need to add instructions to:
- [ ] Uninstall Anaconda
- [ ] Remove any `conda` config from disk
- [ ] Check the uninstall is complete
And this before installing `pyenv`.

[Resource](https://docs.anaconda.com/anaconda/install/uninstall/)

Fixes https://github.com/lewagon/data-setup/issues/234

**Comment by gmanchon** [comment]
+1, we recently had [the issue](https://lewagon-alumni.slack.com/archives/C015E0C601F/p1666438324176439?thread_ts=1666437901.409739&cid=C015E0C601F) again. Even if it was not the case we can address in the setup the possibility that conda is installed and that it takes precedence over pyenv
