### ISSUE TITLE
Virtual environment for Windows

### ISSUE THREAD

**Issue by The-Pavel** [lewagon/data-setup#18]
The **Virtual Environment** step in the Windows setup could use some screenshots to show how the terminal should look like after the virtual environment is successfully created. Some students fail this step and just continue, creating lots of backtracking after.

Now it tells you to run `python -m venv lewagon` and after that *Awesome! The virtual environment has been created.* But if this step fails, or if the `bash` and `git` config commands after that fail, the student has no feedback whether they can continue or not.

**Comment by barangerbenjamin** [comment]
Fixed with #28
