### ISSUE TITLE
Students are asked protocol for github-cli before unique code

### ISSUE THREAD

**Issue by Vin0uz** [lewagon/data-setup#197]
In the [github-cli](https://github.com/lewagon/data-setup/blob/master/macOS.md#github-cli) part of the setup, it's said to students they'll be prompted a unique code after running `gh auth login -s 'user:email' -w`

In the newest version of `github-cli` (2.5.0), it is proposing to pick a protocol (HTTPS/SSH) and it can be confusing for students. 

Also, if they pick SSH because they noticed it's coming just after, it messes up the manual a bit (overwritting key or not etc.) so it might be worth it to rearrange it to keep it as simple as possible🙏

**Comment by dmilon** [comment]
Hi @Vin0uz :wave: Thank you for your feedback :pray: This has been fixed by https://github.com/lewagon/setup/pull/369 :heavy_check_mark:
