### ISSUE TITLE
Misleading instructions

### ISSUE THREAD

**Issue by Benlecoq** [lewagon/data-setup#20]
@ssaunier @krokrob Hey lads! 

"under in the next 2bis section. ⚠️ DO NOT SKIP IT!" : There is no section 2bis. Isn't it supposed to mean "section 3"? 

It is a little unclear and a few students skipped section 3. They got errors down the line because the dotfiles were not installed.

**Comment by ssaunier** [comment]
Thanks @Benlecoq , I fixed it with https://github.com/lewagon/data-setup/commit/d2c25152ca1d95e835a6b5b1dea14f73991ceb1f 🙏
