### ISSUE TITLE
Aliases suggestion

### ISSUE THREAD

**Issue by E-Dmz** [lewagon/data-setup#200]
alias ez="exec zsh" #apple (linux?)
alias ws="wsl.exe --shutdown" #windows, please check
alias rc="code ~/.zshrc"
alias cl="clear"

**Comment by brunolajoie** [comment]
`wsl.exe --shutdown` needs to be executed in powershell, so it's harder to add as alias.
 @dmilon have you heard about aliases for powershell?

**Comment by E-Dmz** [comment]
you can run `wsl**.exe** --shutdown` in the ubuntu terminal under wsl
It does the same thing as opening powershell and running `wsl --shutdown`
It's a tremendous gain of time.
Vincent Moreau showed me that

**Comment by brunolajoie** [comment]
ahhh! soo good! In that case, it's definitely worth creating an alias, thanks @E-Dmz !

**Comment by brunolajoie** [comment]
No alias needed, but i've updated the [common setup error guide](https://www.notion.so/lewagon/Setup-Common-Errors-f09ad57cc4ae4a9a966b63dbf4e5620d#00576d72abd94fd68eac8b9b1cea94bc) here. Thanks!
