### ISSUE TITLE
python 3.8.12 installation poses issues with M1

### ISSUE THREAD

**Issue by brunolajoie** [lewagon/data-setup#201]
Can someone with M1 describes the error?

**Comment by gmanchon** [comment]
https://lewagon-alumni.slack.com/archives/C015E0C601F/p1647521525595919

**Comment by brunolajoie** [comment]
Let's at least bumb to 3.8.13 everyone, and investigate if 3.9.xxx can be a good option for everyone too!

**Comment by Bruncky** [comment]
Indeed 3.8.13 works without issues.

I've been on 3.9.13 on a **fully native** (= **NO** Rosetta at all) for about 1.5 months (including teaching/TAing with it), and I've had no issues so far. Obviously, we should probably test this properly before, but at least on my side, it's all good.

I've also been on the macOS Ventura Beta for about 2 weeks and all has been fine, so I'm hoping we'll have no issues with students on Ventura!

@brunolajoie @gmanchon

**Comment by gmanchon** [comment]
@Bruncky I'm having a look at the setup, what install method did you use on this NO rosetta setup for tensorflow ?

**Comment by Bruncky** [comment]
@gmanchon, simpler than I thought: all I did was install `tensorflow-macos` and `tensorflow-metal` for the GPU!

There's one big caveat: if a student installs the normal TF by accident, the env gets messed up beyond repair, and the **only** way to fix the situation is to completely delete and recreate the env from scratch. This is something I learned from @vtmoreau when he helped me with a ticket! A good solution is adding this to all of our requirements.txt on setup day:

```
tensorflow-macos<=2.8.0; sys_platform == 'darwin' and 'ARM' in platform_version
protobuf<=3.20.1; sys_platform == 'darwin' and 'ARM' in platform_version
tensorflow==2.9.1; sys_platform == 'darwin' and 'ARM' not in platform_version
tensorflow==2.9.1; sys_platform != 'darwin'
```

This will make sure that the correct version of TF gets installed on the correct machine architecture 😄

**Comment by gmanchon** [comment]
@Bruncky same here 🎉 works fine with :
- silicon terminal
- python 3.10.6
- tf-macos 2.10.0
- tf-metal 0.6.0

**Comment by Bruncky** [comment]
@gmanchon, this is great news then! If this works for all students it means a much easier setup for Apple Silicon people

**Comment by gmanchon** [comment]
Fixed by https://github.com/lewagon/data-setup/pull/244
