### ISSUE TITLE
Inconsistency between .zshrc file and  .../lewagon/data-setup/blob/master/WINDOWS.md

### ISSUE THREAD

**Issue by leetoo** [lewagon/data-setup#206]
Small thing but anyway. I'm encounter that number of plugis in instruction .../lewagon/data-setup/blob/master/WINDOWS.md different from in the dotfile .../dotfiles/blob/master/zshrc

`plugins=(git gitfast last-working-dir common-aliases zsh-syntax-highlighting history-substring-search pyenv)`

![image](https://user-images.githubusercontent.com/3446794/162451948-500430d5-183b-4c8b-9aed-1004f152135a.png)

To avoid probable conflict between 'git' and 'gitfast' plugins (it could happen in the future releases of plugins), I propose choosing one plugin, either 'git' or 'gitfast'. Alternatively, ignore it and add the 'git' plugin to the instruction to avoid confusion from future students.

**Comment by julesvanrie** [comment]
Screenshot has been removed. Inconsistency is also gone (`pyenv` is no longer in the plugins - we use a different method now).

As to `git` and `gitfast`, from what I can find, they serve a different purpose (shortcuts vs completion) and so far we didn't really encounter any problems with it.
