### ISSUE TITLE
Suggestion - GCP/Kitt/Slack

### ISSUE THREAD

**Issue by WenfangZh** [lewagon/data-setup#208]
Consider putting the GCP Setup after the Kitt/Slack setup.

While it makes sense to have the Kitt setup near/at the end, so that the workflow leads naturally to the exercises on Kitt, this assumes that all students will finish the setup on time, which frequently does not happen.

Suggestion:
Move GCP setup to the end of the setup, as GCP is much less vital to set up early on than Kitt/Slack. While this slightly disrupts workflow for many students, this only represents a minor disruption to them, whereas not having Kitt/Slack set up by the end of the day will be a significant impediment to start Day 2 the next day

**Comment by brunolajoie** [comment]
Thanks for the suggestion.
It's the responsibility of the batch manager to suggest students to go to Kitt before GCP if needed. 
Part Time/Full Time, large/small classes are all different.
