### ISSUE TITLE
pyenv virtualenv installation suggestion

### ISSUE THREAD

**Issue by vacarme** [lewagon/data-setup#209]
If pyenv is installed with brew why pyenv virutalenv isn't ?

[source](https://github.com/pyenv/pyenv-virtualenv#installing-with-homebrew-for-macos-users)

**Comment by brunolajoie** [comment]
For reference, current setup uses git clone which is common to all OS

```bash
git clone https://github.com/pyenv/pyenv-virtualenv.git $(pyenv root)/plugins/pyenv-virtualenv
exec zsh
```
