### ISSUE TITLE
bump to tensorflow 2.9?

### ISSUE THREAD

**Issue by brunolajoie** [lewagon/data-setup#211]
- [ ] Check that everyone can install 2.9 M1 and WLS2 user)
- [ ] Update the requirements.txt on setup day
- [ ] Improve DL challenges thanks to this new version (cf https://github.com/lewagon/data-solutions/issues/1031)

**Comment by brunolajoie** [comment]
2.10 is stable now

**Comment by gmanchon** [comment]
Solved by https://github.com/lewagon/data-setup/pull/244
