### ISSUE TITLE
Installing python: python-dev not found [Ubuntu 22.04]

### ISSUE THREAD

**Issue by julesvanrie** [lewagon/data-setup#219]
**Data science content type (pick one)**
- [x] Setup

**Content URL**
https://github.com/lewagon/data-setup/blob/master/LINUX.md#installing-python-with-pyenv

**Description**

When executing the "Let's install dependencies code", an error message related to the `python-dev` occurs: the package is not found. This results in no dependencies being installed at all.

System: Ubuntu 22.04 LTS fresh install (oh, the joys of forgetting to update a non-LTS version of Ubuntu in time...).

**Screenshots**

When executing the "Let's install dependencies code", the following error occurs:
```
Package python-dev is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  python2-dev:i386 python2:i386 python2-dev python2 python-dev-is-python3

E: Package 'python-dev' has no installation candidate
```

**Potential solutions**
I've seen a screenshot of a recent WSL install where it could not find this package either, but replaced it by `python-dev-is-python2`. (Which made me wonder if `python-dev-is-python3` would not make more sense?)

I took another approach to test if I could just omit `python-dev` (knowing that `python3-dev` package is installed), which seems to work.

I haven't thoroughly tested, but I could continue setup up until and including the jupyter part without problems. Will update this issue if I encounter any problems later on.

**Comment by tomasaltilio** [comment]
I've encountered the same issue when performing the setup on Pop OS 22.04 LTS
It seems that the `python-dev` package has been merged to `python` . Same applies to the `ncurses` package.

https://wiki.termux.com/wiki/No_more_-dev_packages
https://github.com/termux/termux-packages/issues/4151

**Comment by gmanchon** [comment]
Same issue in content https://github.com/lewagon/teachers/issues/674. I just tested the setup and python works well without `python-dev`
