### ISSUE TITLE
Config SublimeText3 Build System to follow pyenv Python version

### ISSUE THREAD

**Issue by brunolajoie** [lewagon/data-setup#22]
With current setup, students will have a Sublime text whose Build system is still python 2.7.7, and does not contain any of the pip modules installed under their pyenv virtualenv. 

For instance, I couldn't build (Cmd-B) a file starting with "import pandas" because pandas was not installed

I've followed the [following steps](https://medium.com/@john.m.smalley/update-sublime-text-3-to-python-3-on-mac-ce57989bdbf3) and it work like a charm.
Do reckon we should update the setup to configure their Build system? Or do you have another alternative in mind? 

How do they do with Ruby?

cc @barangerbenjamin

**Comment by barangerbenjamin** [comment]
Sublime probably takes the default python shipped with macOS to build.

Do our students use the build options often? If so we can update the guidelines following the link you've provided.
I've never had a student encountering the problem so far
