### ISSUE TITLE
Bump mlflow version to > 1.26

### ISSUE THREAD

**Issue by gmanchon** [lewagon/data-setup#223]
The current setup uses mlflow==1.22.0.

The https://mlflow.lewagon.ai server uses 1.26.1.

We had a student who could not save his model to MLflow until he `pip install -U pip mlflow`.

**Comment by gmanchon** [comment]
@krokrob, in the latest version of the [data setup](https://github.com/lewagon/data-setup/pull/244) we intentionally removed mlflow and prefect from the list of dependencies, which prevents us from asserting the versions that will get installed during the mlflow week. Worse, there is more risk than pip installing independently these packages with fixed versions will cause issues with the versions of other packages installed during the setup, since the constraints will be handled by pip instead of poetry.

We can go in two directions :
- Module based dependencies (.python_version in each myriad challenge with content determined by the module of the challenge)
- Add mlflow and prefect to the global package list to increase our chances of keeping coherent packages throughout the bootcamp

**Comment by brunolajoie** [comment]
I'm not sure to understand something (sorry if stupid question)

- Why don't we simply not install any package from MLOPS during data-setup ? And create a requirement-mlops.txt specifically for the MLOPS?

**Comment by gmanchon** [comment]
Sorry, I missed your comment.

The current approach of the setup is to have a single env during the program. So it does not matter at which moment the packages are installed : the dependencies need to be resolved all together, or something will (probably) break.

With this approach, it is best to resolve all the dependencies during the setup day. The latest setup process using poetry allows to resolve the package version constraints all together (3 month old packages + specific versions for python, pandas, tensorflow, etc).

Another option would be to go for a per module setup. It is interesting to move towards a modular approach to the program. But if we go for this, we need to :
- update glovebox to be able to handle multiple images per program
- update the data-solutions tests gha to handle a per module image

**Comment by brunolajoie** [comment]
> The current approach of the setup is to have a single env during the program.

Not for MLOPS module, we make student create their own `taxifare-env` on unit 0701 up to 0705

**Comment by gmanchon** [comment]
Glovebox and the data-solutions GHA do not know that 😉

**Comment by krokrob** [comment]
@gmanchon could you check that there are any cloud test (vs local test) involving the `mlflow` package. If not, there is no need `data-solutions` nor Glovebox needs it

**Comment by gmanchon** [comment]
That's a good point 😁 There are none, and it is more convenient to have a blank setup for the students in the mlops week, thanks @brunolajoie @krokrob 🙏

I added a https://github.com/lewagon/taxi-fare/pull/183 PR to fix the mlflow minor version so that the students env matches the prod and content writing versions
