### ISSUE TITLE
Add "pylint" for "SublimeLinter" for students in setup day 0

### ISSUE THREAD

**Issue by brunolajoie** [lewagon/data-setup#23]
Suggested process (or maybe integrate it directly in the `.dotfile`setup process? Not sure best practice)

- after pyenv setup
- `pip install pylint`
- Then add the following to `sublimeLinter.sublime-settings - User`
```json
{
  "paths": {
    "osx": [
      "~/.pyenv/shims",
    ]
  },
  "linters": {
    "pylint": {
      "disable": false
    },
  }
}
```

**Comment by krokrob** [comment]
I propose https://github.com/SublimeLinter/SublimeLinter-flake8 @brunolajoie @gmanchon @barangerbenjamin

**Comment by krokrob** [comment]
then https://packagecontrol.io/packages/AutoPEP8 for the code formatting

**Comment by krokrob** [comment]
replace `pylint` with `flake8` to check students code when they `make`

**Comment by brunolajoie** [comment]
✅ flake8 is more stable on my computer
