### ISSUE TITLE
Python packages step: error in "visions" requirement results in pip install failing

### ISSUE THREAD

**Issue by julesvanrie** [lewagon/data-setup#238]
**Setup step**: Python packages

When running `pip install -r https://raw.githubusercontent.com/lewagon/data-setup/master/specs/releases/apple_silicon.txt`, an error is generated and nothing is installed.

Error is generated when installing `visions` package.

**Root cause**: error in requirements.txt (all platforms) introduced in last commit

`visions[type_image_path]` (underscores) was changed into `visions[type-image-path]` (dashes) which doesn't work. Need to revert to the one with underscores. (Tested on student machine.)

**System**: M2 mac, but should be the same on other platforms.

Encountered this because student bought a new laptop two days after setup day, and we went through the whole process again.

**Comment by gmanchon** [comment]
Hello @julesvanrie 👋,

This syntax was generated by poetry but is not supported by pip.

The requirements.txt are going to be platform specific again in the next setup release, which should avoid this issue altogether...

Thanks for reporting 🙏
