### ISSUE TITLE
Dependency conflict in python packages (nbclassic==0.4.6)

### ISSUE THREAD

**Issue by b-fa-ce** [lewagon/data-setup#242]
The issue arises when running 
`pip install -r https://raw.githubusercontent.com/lewagon/data-setup/master/specs/releases/apple_intel.txt`

with following error message:
```
ERROR: Cannot install -r https://raw.githubusercontent.com/lewagon/data-setup/master/specs/releases/apple_intel.txt (line 128), -r https://raw.githubusercontent.com/lewagon/data-setup/master/specs/releases/apple_intel.txt (line 165) and nbclassic==0.4.6 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested nbclassic==0.4.6
    jupyterlab 3.4.8 depends on nbclassic
    notebook 6.5.1 depends on nbclassic==0.4.5

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
```

The issue might be resolved with a less strict dependency requirement on `nbclassic` according to [pip dependency resolution](https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts). 

Changing `nbclassic==0.4.5` to `nbclassic>=0.4.5` in the file 'ttps://raw.githubusercontent.com/lewagon/data-setup/master/specs/releases/apple_intel.txt' resolves the issue.

**Comment by gmanchon** [comment]
Hello @b-fa-ce, the previous version of the setup indeed had issues the coherence of the package versions. This is solved by the [latest release](https://github.com/lewagon/data-setup/pull/244) of the data setup. You can upgrade your environment by creating a new virtual env and installing the requirements. Thanks for reporting ! 🙏
