### ISSUE TITLE
jupyter notebook extensions - no extensions tab

### ISSUE THREAD

**Issue by b-fa-ce** [lewagon/data-setup#243]
Issue: There is no extensions tab in jupyter notebook with `notebook==6.5.1`

Possible work-around: [reverting to older version](https://stackoverflow.com/a/65599505)
```
pip install notebook==6.1.5
```

**Comment by gmanchon** [comment]
Hello @b-fa-ce, this is addressed by the [latest version of the setup](https://github.com/lewagon/data-setup/pull/244) which uses `notebook==6.4.12`. Thanks for reporting ! 🙏
