### ISSUE TITLE
Ubuntu [No WSL] VSCode install

### ISSUE THREAD

**Issue by gmanchon** [lewagon/data-setup#245]
Following this [slack issue](https://lewagon-alumni.slack.com/archives/C015E0C601F/p1666682881893129?thread_ts=1666444027.540919&cid=C015E0C601F), it seems that we need to update the WSL VSCode setup from a _snap based method_ to this :

```
On Ubuntu flavours, one needs to install VS Code using the instructions from Microsoft. For instructions see https://code.visualstudio.com/docs/setup/linux. Don't use the Snap based method.
The default installation method on Ubuntu would be a snap based install. That unfortunately runs with some snap core that doesn't appear to have the necessary libc libraries for this work.
That problem does not exist if VSCode is installed from Microsoft's own deb archives.
This is not a general VSCode issue with python, but something related either to jupyter or tensorflow. 
VS code version: 1.72.2
Ubuntu version: 20.04.5 
```

**Comment by vtmoreau** [comment]
Hey @gmanchon 

I'll look into it next week.

It's a bit strange that it only happened to one person though.
Lots of students on the current batch are using VS Code to open notebooks without any trouble 🤔

Are we confortable updating the whole setup for one case that has not yet be reproduced ?

**Comment by gmanchon** [comment]
@vtmoreau hahaha we are not 😉 Thanks for your investigation 🙏 Maybe this is just a one off case 🙌

**Comment by gmanchon** [comment]
@vtmoreau if this is uncommon and not unreproducible let's close this issue 👌

**Comment by vtmoreau** [comment]
Actually this happened on a true Ubuntu without WSL
Back to 🕵️

**Comment by vtmoreau** [comment]
So final words:
The student reported that:
[On Ubuntu flavours, one needs to install VS Code using the instructions from Microsoft. For instructions see https://code.visualstudio.com/docs/setup/linux. Don't use the Snap based method.](https://lewagon-alumni.slack.com/archives/C015E0C601F/p1666682881893129?thread_ts=1666444027.540919&cid=C015E0C601F)

In the Linux Setup we already suggest to install VS Code from the deb archive
<img width="794" alt="image" src="https://user-images.githubusercontent.com/36458245/201864564-2799ead1-5aa5-49f4-a000-29a30911da38.png">
