### ISSUE TITLE
Windows: Suggest that students open Sublime Text once before using the "Run" tool

### ISSUE THREAD

**Issue by Disco-Chef** [lewagon/data-setup#25]
If Sublime hasn't been launched at all, this step:

https://github.com/lewagon/data-setup/blob/master/WINDOWS.md#sublime-text-3---package

will throw an error and not allow it.

However, if the app has been launched for the first time, the step works fine. I suggest we add a small note to have the students open Sublime once.

**Comment by krokrob** [comment]
@gmanchon there is no Sublime Text anymore for Windows setup right?

**Comment by Disco-Chef** [comment]
It's the data setup and yes there is

**Comment by krokrob** [comment]
Hi @Disco-Chef we are curently updating the data-setup to move Windows users under the WSL2 which is not yet compatible with Sublime Text but fully operational with VScode. Thanks for the reporting.

**Comment by Disco-Chef** [comment]
Sorry, I thought you were asking if STT was in the current data windows setup (using git bash). Awesome that we are finally moving windows data students to wsl2

**Comment by gmanchon** [comment]
No Sublime for Windows users with WSL2 setup at the moment, but we might want to switch back to Sublime as soon as Microsoft fixes the disk access issue...

**Comment by barangerbenjamin** [comment]
Don't think it's nearly near there for Microsoft ^^

Also Jupyter notebook native integration with VScode is something to watch on 👀 

Closing since we're migrating to VScode with #28
