### ISSUE TITLE
generate en_US.UTF-8 locale 

### ISSUE THREAD

**Issue by TulipeSoyeuse** [lewagon/data-setup#254]
ubuntu 22.04 LTS doesn't have locale en_US.UTF-8 by default. 
`sudo locale-gen en_US.UTF-8` solve it. 
this issue impact every WLS user

**Comment by gmanchon** [comment]
Hello @TulipeSoyeuse, did you encounter the issue on Windows 10 or Windows 11 ?

What issue did the problem cause on the machine ?
