### ISSUE TITLE
fix scipy version to 1.10.0

### ISSUE THREAD

**Issue by gmanchon** [lewagon/data-setup#265]
jupyter kernel crashes with data setup version during `PCA().fit` on MBP Pro M1 for macos >= 13.1

[slack thread](https://lewagon-alumni.slack.com/archives/C015E0C601F/p1676466923989959)

**Comment by julesvanrie** [comment]
Fixed by #271 
Intel and linux are still on older versions, but let's not change that now. Will be aligned when we do an update of the requirements.
