### ISSUE TITLE
m1 student and brew

### ISSUE THREAD

**Issue by TulipeSoyeuse** [lewagon/data-setup#266]
found out monday that many m1 student had a python3.10.9 installed on their machine through homebrew.
Because homebrew is referenced in the PATH before pyenv ( cd .zprofile ) those student used homebrew pip instead of pyenv during all bootcamp.

fix it just by add the pyenv export path after eval homebrew

**Comment by ssaunier** [comment]
👋 Is this related to https://github.com/lewagon/setup/issues/421 ?

**Comment by gmanchon** [comment]
Hello @TulipeSoyeuse, we use homebrew in order to install pyenv, therefore homebrew needs to be referenced before pyenv in the PATH. The solution would be to uninstall the students hombrew python 3.0.19 install. Maybe this is a side effect of the prepwork @krokrob ?

**Comment by krokrob** [comment]
I have no idea of the prepwork requiring any setup of Python

**Comment by gmanchon** [comment]
In this case @TulipeSoyeuse the solution does not require steps other than `brew uninstall python` or `brew uninstall python3` depending on the package 🙌 Thanks for reporting 🙏
