### ISSUE TITLE
"Linking your default browser to Ubuntu" is outdated

### ISSUE THREAD

**Issue by Eschults** [lewagon/data-setup#267]
ℹ️ Transferring https://github.com/lewagon/data-challenges/issues/2660 here

❓ @krokrob is there a script to run to fetch fresh content from https://github.com/lewagon/setup partials?

---

Issue on Kitt Demo (00-Setup/01-Check)
[yannklein](https://kitt.lewagon.com/users/yannklein):
The Windows data-setup has out-dated content.

The "Linking your default browser" is outdated (link: https://github.com/lewagon/data-setup/blob/master/WINDOWS.md#linking-your-default-browser-to-ubuntu)

The Web setup has the updated version, we can maybe use it to update data-setup.
(link: https://github.com/lewagon/setup/blob/master/windows.md#linking-your-default-browser-to-ubuntu)

:octocat:[ exercise](https://github.com/lewagon-data/check)

:octocat:[ solution](https://github.com/lewagon/data-solutions/tree/master/00-Setup/01-Check)

**Comment by krokrob** [comment]
@Eschults we just need to run the setup builder
