### ISSUE TITLE
Check the locale issue

### ISSUE THREAD

**Issue by v-natalia** [lewagon/data-setup#284]
I'm not sure that the web-dev owner can modify the data-setup so here is an issue that mentions some problems with the current section Check the locale [Issue](https://github.com/lewagon/setup/issues/462)

**Comment by julesvanrie** [comment]
Thanks for reporting @v-natalia !
 
Great timing, I was just doing a fresh data-setup on my brand new laptop to check if the setup still works as expected.

We don't have the locale part in data-setup yet, but it would be included in a PR I just made (and am pausing now).
(Some parts of the web setup are automatically included in data-setup when we make an update. This is one of them.)

**Comment by julesvanrie** [comment]
Solved following update to web setup, and integrating in data-setup.

**Comment by v-natalia** [comment]
Thanks @julesvanrie !
