### ISSUE TITLE
email privacy

### ISSUE THREAD

**Issue by Laiagdla** [lewagon/data-setup#289]
Hi! regarding the part of signing in to github and dotfiles. 
I just discovered that the name and email, specified in the "gitconfig" is being used to sign commits, even in public repos.
Would it be considered a useful warning for people to know that the full name and this email might be shown publicly at some point? if they create or contribute to a public repo, for example.

or also implement this posibility?
[https://stackoverflow.com/questions/7372970/git-commit-with-no-email/71542189#71542189](url)
> When contributing to github, always use the anonymous noreply email address provided by github - which you can find here: https://github.com/settings/emails (have to tick "Keep my email addresses private" to see it).

gitconfig looking like this: 
```
[user]
    name = Joe Blogs
    email = ID+username@users.noreply.github.com
```

**Comment by julesvanrie** [comment]
Thanks for reporting.

Created a new issue in teachers so I can discuss with WebDev and Data Engineering track owners because this part is common to all three setups.

**Comment by ssaunier** [comment]
Fixed by https://github.com/lewagon/setup/pull/467

**Comment by julesvanrie** [comment]
This was still to do for DS, but I just did it.

> This notice is in the dotfiles part and that is a separate partial for DS <> web (catering for case where the student did web bootcamp before).

**Comment by ssaunier** [comment]
Sorry I forgot about the other repo, thanks for getting on it so quick! 🙏
