### ISSUE TITLE
lzma errors still present with the python 3.8.5 setup

### ISSUE THREAD

**Issue by gmanchon** [lewagon/data-setup#30]
although the setup deals with this by running `brew install xz` before installing `pyenv`, a lot of students on macos still get the lzma warning :

`UserWarning: Could not import the lzma module. Your installed Python is incomplete. 
Attempting to use lzma compression will result in a RuntimeError. warnings.warn(msg)`

in order to solve this it was necessary to upgrade python to 3.8.6 and create a new virtual env:

```bash
brew install xz
pyenv install 3.8.6
pyenv virtualenv 3.8.6 data
pyenv activate data
````

(then update the `~/.zshrc` in order to use the new env as default, and rerun the setup `pip install ...` steps)

which is very strange, since these steps exactly replicate the setup

**Comment by barangerbenjamin** [comment]
Fixed with #26 merged
