### ISSUE TITLE
Update needed for new macs - 👉  Setup for Apple Silicon 👈  Open using Rosetta not needed anymore

### ISSUE THREAD

**Issue by IdoKun** [lewagon/data-setup#304]
Hello for the new macs, with Apple silcon and the new OS the Rosetta box is not needed and does not appear anymore.
Students can just move on

**Comment by julesvanrie** [comment]
@IdoKun Can you check again? Because I still see the option. See screenshot. Running macOS Sequoia.

![Image](https://github.com/user-attachments/assets/62934e69-5f8a-403a-83ee-21f74f911818)

**Comment by IdoKun** [comment]
Well for my machine you are correct. I have an Apple M1
But with my wife's computer M3 and the students with M3 you don't have the
ticker for Rosseta

**Comment by julesvanrie** [comment]
Interesting. Probably not related to M3 itself but more to macOS it got shipped with.

I’ll adapt the setup “if you don’t see it, just go ahead” or something like that.

**Comment by IdoKun** [comment]
Thank you. In did it didn’t any causes up the road.
