### ISSUE TITLE
Add docstring to SublimeText

### ISSUE THREAD

**Issue by brunolajoie** [lewagon/data-setup#37]
Student really needs to be able to code in their text editor starting week7, and being able to display the docstring in your editor makes their life much easier.

I have found a SublimeText3 docstring that works well using [AnacondaIDE](http://damnwidget.github.io/anaconda/)

It works well on my end
![image](https://user-images.githubusercontent.com/22095643/101014960-f0ee0880-3566-11eb-8080-69fe26766ceb.png)

but I had to add the following file in my `User/Anaconda.sublime-setting` to make it work with pyenv and stop interfering with Flake8

```
{
  "anaconda_linting": false,
  "python_interpreter": "/Users/brunolajoie/.pyenv/shims/python"

}
```

Shortcut to display docstring is then Cmd-Shift-D
🚀

**Comment by krokrob** [comment]
It is `Ctrl` + `Opt` + `d` right? http://damnwidget.github.io/anaconda/IDE/#display-signatures

**Comment by krokrob** [comment]
Works like a charm without any other config
