### ISSUE TITLE
WSL: "Please enable the Virtual Machine Platform Windows feature and ensure virtualization is enabled in the BIOS."

### ISSUE THREAD

**Issue by brunolajoie** [lewagon/data-setup#72]
ISSUE: Some Windows Students encounters the follwing error 

> "Please enable the Virtual Machine Platform Windows feature and ensure virtualization is enabled in the BIOS."

at step https://github.com/lewagon/data-setup/blob/master/WINDOWS.md#upgrade-to-wsl-2

SOLUTION:

Manually allow WSL as decribed here
![image](https://user-images.githubusercontent.com/22095643/113554974-74456680-95fa-11eb-9705-50e9c476865e.png)

https://www.configserverfirewall.com/windows-10/please-enable-the-virtual-machine-platform-windows-feature-and-ensure-virtualization-is-enabled-in-the-bios/#:~:text=To%20enable%20WSL%202,%20Open,Windows%20feature%20on%20or%20off.&text=Ensure%20that%20the%20Virtual%20Machine,Windows%20will%20enable%20WSL%202

**Comment by barangerbenjamin** [comment]
Most often than not it's probably due to the student not restarting their machine after running the 3 commands:
```Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux
dism.exe /online /enable-feature /featurename:Microsoft-Windows-Subsystem-Linux /all /norestart
dism.exe /online /enable-feature /featurename:VirtualMachinePlatform /all /norestart```

**Comment by gmanchon** [comment]
Does running `dism.exe` without the `/norestart` trigger a restart ? Or do we add a `shutdown /r`?

**Comment by krokrob** [comment]
I think I'm going to close this one, there was no report about that issue since then
