### ISSUE TITLE
Fix GCP Service Account Key paths for Windows/Linux

### ISSUE THREAD

**Issue by krokrob** [lewagon/data-setup#76]
cf https://github.com/lewagon/data-setup/pull/75

**Comment by gitgithan** [comment]
Thanks for helping to open issue.
I have tested that this way of setting up the key works correctly by connecting to Google Cloud Storage with python. Also confirmed by assigning None to GOOGLE_APPLICATION_CREDENTIALS and running the same code gets me `DefaultCredentialsError` , so indeed the JSON key at that path is found and used.

**Comment by gmanchon** [comment]
@gitgithan this issue is addressed by https://github.com/lewagon/data-setup/pull/98, thanks for reporting 🙏
