### ISSUE TITLE
VS code extensions instructions

### ISSUE THREAD

**Issue by contatc2** [lewagon/data-setup#79]
Students are confused where to type those on windows:
VS Code Extensions
Let's gain time now and add other extensions that will be helpful during your Bootcamp:
 --> add to instruction: "Please copy those in your powershell"

**Comment by brunolajoie** [comment]
@contatc2 I'm a bit confused, but should we install VS code extension
-  LOCAL (from powershell as you suggest)
- or only for WSL2 (from linux terminal)?

Look below what happens when I install Jupyter them from powershell:

![image](https://user-images.githubusercontent.com/22095643/135749180-017a93e6-2cac-43bc-aee9-e6614f667c94.png)

cc @vtmoreau @Yanka13 any idea?

Some extentions wants to run local, other WSL

I'm lost 🤷

**Comment by migasar** [comment]
According to the [official doc](https://code.visualstudio.com/docs/remote/wsl#_managing-extensions)   
(as long as the extension `remote development - WSL` is working),   

you can install :
- in local : Theme/UI extensions
- in WSL : all the other extensions 

> Managing extensions
> 
> VS Code runs extensions in one of two places: locally on the UI / client side, or in WSL. While extensions that affect the VS Code UI, like themes and snippets, are installed locally, most extensions will reside inside WSL.
> 
> If you install an extension from the Extensions view, it will automatically be installed in the correct location. Once installed, you can tell where an extension is installed based on the category grouping. There will be Local - Installed category and one for WSL.
> 
> Local extensions that actually need to run remotely will appear dimmed and disabled in the Local - Installed category. Select Install to install an extension on your remote host.
> 

![](https://code.visualstudio.com/assets/docs/remote/wsl/architecture-wsl.png)

**Comment by brunolajoie** [comment]
Ok, I've tested it, we should install everything from the WSL env! 

Problem is, they don't yet have the ubuntu terminal configured at that stage of the setup. 

So, I suggest to make them install these extensions manually instead
