### ISSUE TITLE
Docker installation - suspended tty

### ISSUE THREAD

**Issue by zzuziak** [lewagon/data-setup#91]
Several students experienced weird error upon adding the GPG key from the Docker installation tutorial for Linux. 

The key message in error is `suspended tty` which means that there is some process running in the background an interfering in the terminal. We couldn't find anything on Google but what worked for **everyone** was to **turn the computer off and on again ♥** and then adding the GPG key, running `sudo apt update` and continuing with the installation.

I can make a PR for it but first wanted to check if it happended as well for any Mac users? If not, I'll update the Ubuntu and Windows docs. 

cc @gmanchon @krokrob , any idea as for macOS?

**Comment by gmanchon** [comment]
@zzuziak I have not encountered this issue during the setup...
