### ISSUE TITLE
Add default editor in shell profile

### ISSUE THREAD

**Issue by AlvaroPata** [lewagon/data-setup#96]
We've had several issues with the students editing their .zshrc files with TextEdit from macos and it saving it with a hidden .txt extension. Zsh wouldn't source these files then.

I suggest the students add the following line to their shell configuration 
`export EDITOR='code'`
so they don't accidentally end up editing their source files with Word or sth.

**Comment by krokrob** [comment]
Hey @AlvaroPata, I can't manage to make that setting override the default behavior of my OS which is to open files without extension with the default text editor. Can you elaborate on your strategy please?

**Comment by dmilon** [comment]
Fixed by https://github.com/lewagon/dotfiles/pull/101
