### ISSUE TITLE
WSL GCP JSON credentials location

### ISSUE THREAD

**Issue by zzuziak** [lewagon/data-setup#97]
Let's update the Windows setup to make sure students store their service account credentials inside Ubuntu, rather than Windows as below:

![image](https://user-images.githubusercontent.com/39556343/119647230-5210dd80-be20-11eb-8126-f4457c1102ac.png)

**Comment by gmanchon** [comment]
This is addressed by https://github.com/lewagon/data-setup/pull/98 👍
